from __future__ import annotations

# Runtime UX save/load diagnostics (deterministic stable codes).
SAVE_WRITE_FAILED = "SAVE_WRITE_FAILED"
SAVE_SERIALIZE_FAILED = "SAVE_SERIALIZE_FAILED"
SAVE_SLOT_INVALID = "SAVE_SLOT_INVALID"
SAVE_IO_PERMISSION = "SAVE_IO_PERMISSION"
LOAD_NOT_FOUND = "LOAD_NOT_FOUND"
LOAD_PARSE_FAILED = "LOAD_PARSE_FAILED"
LOAD_SCHEMA_INVALID = "LOAD_SCHEMA_INVALID"
LOAD_APPLY_FAILED = "LOAD_APPLY_FAILED"
LOAD_FALLBACK_TO_START_SCENE = "LOAD_FALLBACK_TO_START_SCENE"
# Backward-compatible alias for older imports.
LOAD_FALLBACK_START_SCENE = LOAD_FALLBACK_TO_START_SCENE


SAVE_LOAD_CODES: tuple[str, ...] = (
    LOAD_APPLY_FAILED,
    LOAD_FALLBACK_TO_START_SCENE,
    LOAD_NOT_FOUND,
    LOAD_PARSE_FAILED,
    LOAD_SCHEMA_INVALID,
    SAVE_IO_PERMISSION,
    SAVE_SERIALIZE_FAILED,
    SAVE_SLOT_INVALID,
    SAVE_WRITE_FAILED,
)


__all__ = [
    "LOAD_APPLY_FAILED",
    "LOAD_FALLBACK_TO_START_SCENE",
    "LOAD_FALLBACK_START_SCENE",
    "LOAD_NOT_FOUND",
    "LOAD_PARSE_FAILED",
    "LOAD_SCHEMA_INVALID",
    "SAVE_IO_PERMISSION",
    "SAVE_LOAD_CODES",
    "SAVE_SERIALIZE_FAILED",
    "SAVE_SLOT_INVALID",
    "SAVE_WRITE_FAILED",
]
