"""Pure monster battle domain model.

This package intentionally stays independent of the Mesh runtime stack.
"""

from __future__ import annotations

from .battle_controller import (
    BattleLogEntry,
    BattlePhase,
    BattleResult,
    BattleSideId,
    InvalidBattleActionError,
    MonsterBattleController,
    MoveAction,
    controller_from_catalog,
)
from .battle_mode import (
    MONSTER_BATTLE_CAPTURE_ATTEMPT_EVENT,
    MONSTER_BATTLE_ENDED_EVENT,
    MONSTER_BATTLE_RESULT_KEY,
    MONSTER_BATTLE_RETURN_CONTEXT_KEY,
    MonsterBattleMode,
    MonsterBattleOverlay,
    start_monster_battle,
)
from .battle_model import (
    BattleStats,
    MonsterInstance,
    Move,
    MoveResolution,
    Species,
    TypeChart,
    compute_damage,
    resolve_move,
    type_multiplier,
)
from .capture import CaptureResult, resolve_capture
from .collection import (
    DEFAULT_POCKET_BALL_COUNT,
    MAX_PARTY_SIZE,
    MONSTER_BOX_KEY,
    MONSTER_INSTANCES_KEY,
    MONSTER_PARTY_KEY,
    POCKET_BALL_COUNT_KEY,
    AddCaughtMonsterResult,
    add_caught_monster,
    consume_pocket_ball,
    ensure_monster_collection,
    get_pocket_ball_count,
    serialize_monster_instance,
)
from .data_load import (
    MonsterCatalog,
    ValidationResult,
    load_monster_catalog,
    load_moves,
    load_species,
    load_type_chart,
    parse_moves,
    parse_species,
    parse_type_chart,
    validate_referential_integrity,
)
from .progression import (
    ExperienceResult,
    apply_experience,
    award_xp_for_victory,
    level_for_experience,
    xp_required_for_level,
)
from .status import (
    POISON,
    SLEEP,
    StatusCondition,
    StatusEvent,
    apply_status,
    can_act,
    tick_end_of_turn,
)

__all__ = [
    "BattleStats",
    "AddCaughtMonsterResult",
    "BattleLogEntry",
    "BattlePhase",
    "BattleResult",
    "BattleSideId",
    "InvalidBattleActionError",
    "CaptureResult",
    "DEFAULT_POCKET_BALL_COUNT",
    "ExperienceResult",
    "MONSTER_BATTLE_CAPTURE_ATTEMPT_EVENT",
    "MONSTER_BATTLE_ENDED_EVENT",
    "MONSTER_BATTLE_RESULT_KEY",
    "MONSTER_BATTLE_RETURN_CONTEXT_KEY",
    "MAX_PARTY_SIZE",
    "MONSTER_BOX_KEY",
    "MONSTER_INSTANCES_KEY",
    "MONSTER_PARTY_KEY",
    "MonsterCatalog",
    "MonsterBattleController",
    "MonsterBattleMode",
    "MonsterBattleOverlay",
    "Move",
    "MoveAction",
    "MoveResolution",
    "MonsterInstance",
    "POCKET_BALL_COUNT_KEY",
    "POISON",
    "SLEEP",
    "Species",
    "StatusCondition",
    "StatusEvent",
    "TypeChart",
    "ValidationResult",
    "add_caught_monster",
    "apply_experience",
    "award_xp_for_victory",
    "compute_damage",
    "consume_pocket_ball",
    "controller_from_catalog",
    "ensure_monster_collection",
    "get_pocket_ball_count",
    "level_for_experience",
    "load_monster_catalog",
    "load_moves",
    "load_species",
    "load_type_chart",
    "parse_moves",
    "parse_species",
    "parse_type_chart",
    "resolve_move",
    "resolve_capture",
    "serialize_monster_instance",
    "start_monster_battle",
    "tick_end_of_turn",
    "type_multiplier",
    "validate_referential_integrity",
    "xp_required_for_level",
]
