from __future__ import annotations

from dataclasses import dataclass

SHORTCUT_SCOPE_GLOBAL = "global"
SHORTCUT_SCOPE_INLINE_RENAME = "text_input.inline_rename"
SHORTCUT_SCOPE_PROJECT_EXPLORER = "project_explorer"
SHORTCUT_SCOPE_PROJECT_EXPLORER_CONTEXT_MENU = "project_explorer.context_menu"
SHORTCUT_SCOPE_PLAYTEST = "playtest"


@dataclass(frozen=True, slots=True)
class ActionDef:
    id: str
    title: str
    keywords: tuple[str, ...]
    group: str | None
    shortcut: str
    enabled: str
    run: str
    in_palette: bool = True
    in_menu: bool = True
    menu_label: str | None = None
    shortcut_scope: str = SHORTCUT_SCOPE_GLOBAL


DEFAULT_ACTION_DEFS: tuple[ActionDef, ...] = (
        ActionDef(
            id="editor.project_explorer.refactor_delete_selected",
            title="Project Explorer: Safe Delete Selected",
            keywords=("delete", "remove", "refactor", "project", "explorer", "files"),
            group="Edit",
            shortcut="Del",
            enabled="_enabled_project_explorer_selection",
            run="_action_refactor_delete_selected",
            in_palette=True,
            in_menu=True,
            shortcut_scope=SHORTCUT_SCOPE_PROJECT_EXPLORER,
        ),
        ActionDef(
            id="editor.project_explorer.refactor_move_selected",
            title="Project Explorer: Safe Move Selected",
            keywords=("move", "refactor", "project", "explorer", "files"),
            group="Edit",
            shortcut="Ctrl+Shift+M",
            enabled="_enabled_project_explorer_selection",
            run="_action_refactor_move_selected",
            in_palette=True,
            in_menu=True,
            shortcut_scope=SHORTCUT_SCOPE_PROJECT_EXPLORER,
        ),
        ActionDef(
            id="editor.project_explorer.refactor_rename_commit",
            title="Project Explorer: Commit Rename",
            keywords=("rename", "commit", "refactor"),
            group="Edit",
            shortcut="",
            enabled="_enabled_inline_rename_active",
            run="_action_refactor_rename_commit",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_INLINE_RENAME,
        ),
        ActionDef(
            id="editor.light_tool.toggle",
            title="Toggle Light Tool",
            keywords=("light", "lighting", "tool"),
            group="Scene",
            shortcut="L",
            enabled="_enabled_always",
            run="_toggle_lights_tool",
            in_palette=True,
            in_menu=True,
            menu_label="Lights Tool",
        ),
        ActionDef(
            id="editor.occluder_tool.toggle",
            title="Toggle Occluder Tool",
            keywords=("occluder", "shadow", "polygon"),
            group="Scene",
            shortcut="O",
            enabled="_enabled_always",
            run="_toggle_occluder_tool",
            in_palette=True,
            in_menu=True,
            menu_label="Occluders Tool",
        ),
        ActionDef(
            id="editor.entity_panels.toggle",
            title="Toggle Entity Panels",
            keywords=("entity", "outliner", "inspector", "panels"),
            group="View",
            shortcut="Ctrl+E",
            enabled="_enabled_always",
            run="_toggle_entity_panels",
            in_palette=True,
            in_menu=True,
            menu_label="Entity Panels",
        ),
        ActionDef(
            id="editor.panel.project_explorer.toggle",
            title="Toggle Project Explorer",
            keywords=("panel", "project", "explorer", "files"),
            group="View",
            shortcut="Ctrl+Alt+4",
            enabled="_enabled_always",
            run="_toggle_project_explorer_panel",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.project_explorer.reveal_current",
            title="Reveal in Project Explorer",
            keywords=("reveal", "project", "explorer", "scene", "asset", "show"),
            group="View",
            shortcut="Ctrl+Shift+E",
            enabled="_enabled_has_reveal_target",
            run="_reveal_current_in_project_explorer",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.project_explorer.copy_path",
            title="Project Explorer: Copy Selected Paths",
            keywords=("project", "explorer", "files", "selection", "copy", "move", "delete", "paths", "path", "copy path", "clipboard"),
            group="Edit",
            shortcut="Ctrl+Shift+C",
            enabled="_enabled_project_explorer_selection",
            run="_copy_project_explorer_path",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.project_explorer.copy_common_parent",
            title="Project Explorer: Copy Common Parent",
            keywords=("project", "explorer", "files", "selection", "copy", "move", "delete", "path", "parent", "folder", "clipboard"),
            group="Edit",
            shortcut="Ctrl+Shift+Alt+C",
            enabled="_enabled_project_explorer_selection",
            run="_copy_project_explorer_common_parent",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.project_explorer.select_all",
            title="Project Explorer: Select All",
            keywords=("project", "explorer", "files", "selection", "copy", "move", "delete", "select", "all"),
            group="Edit",
            shortcut="Ctrl+A",
            enabled="_enabled_project_explorer_active",
            run="_project_explorer_select_all",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.project_explorer.clear_selection",
            title="Project Explorer: Clear Selection",
            keywords=("project", "explorer", "files", "selection", "copy", "move", "delete", "clear"),
            group="Edit",
            shortcut="Escape",
            enabled="_enabled_project_explorer_active",
            run="_project_explorer_clear_selection",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.project_explorer.invert_selection",
            title="Project Explorer: Invert Selection",
            keywords=("project", "explorer", "files", "selection", "copy", "move", "delete", "invert"),
            group="Edit",
            shortcut="Ctrl+I",
            enabled="_enabled_project_explorer_active",
            run="_project_explorer_invert_selection",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.project_explorer.context_menu.open",
            title="Project Explorer: Open Context Menu",
            keywords=("project", "explorer", "context", "menu"),
            group="Edit",
            shortcut="Shift+F10",
            enabled="_enabled_project_explorer_active",
            run="_project_explorer_context_menu_open",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_PROJECT_EXPLORER,
        ),
        ActionDef(
            id="editor.project_explorer.context_menu.close",
            title="Project Explorer: Close Context Menu",
            keywords=(),
            group="Edit",
            shortcut="Esc",
            enabled="_enabled_project_explorer_context_menu_open",
            run="_project_explorer_context_menu_close",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_PROJECT_EXPLORER_CONTEXT_MENU,
        ),
        ActionDef(
            id="editor.project_explorer.context_menu.up",
            title="Project Explorer: Context Menu Up",
            keywords=(),
            group="Edit",
            shortcut="Up",
            enabled="_enabled_project_explorer_context_menu_open",
            run="_action_project_explorer_context_menu_up",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_PROJECT_EXPLORER_CONTEXT_MENU,
        ),
        ActionDef(
            id="editor.project_explorer.context_menu.down",
            title="Project Explorer: Context Menu Down",
            keywords=(),
            group="Edit",
            shortcut="Down",
            enabled="_enabled_project_explorer_context_menu_open",
            run="_action_project_explorer_context_menu_down",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_PROJECT_EXPLORER_CONTEXT_MENU,
        ),
        ActionDef(
            id="editor.project_explorer.context_menu.activate",
            title="Project Explorer: Context Menu Activate",
            keywords=(),
            group="Edit",
            shortcut="Enter",
            enabled="_enabled_project_explorer_context_menu_open",
            run="_project_explorer_context_menu_activate",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_PROJECT_EXPLORER_CONTEXT_MENU,
        ),
        ActionDef(
            id="editor.project_explorer.delete_selected",
            title="Project Explorer: Delete Selected",
            keywords=("project", "explorer", "files", "selection", "copy", "move", "delete"),
            group="Edit",
            shortcut="",
            enabled="_enabled_project_explorer_selection",
            run="_project_explorer_delete_selected",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.project_explorer.safe_rename_asset",
            title="Safe Rename Asset",
            keywords=("rename", "asset", "refactor", "references", "project", "explorer"),
            group="Edit",
            shortcut="F2",
            enabled="_enabled_project_explorer_file_selection",
            run="_safe_rename_selected_asset",
            in_palette=True,
            in_menu=True,
        ),

        # --- Inline Rename Actions (not in palette/menu, scoped to inline rename mode) ---
        ActionDef(
            id="editor.project_explorer.inline_rename.commit",
            title="Commit Inline Rename",
            keywords=(),
            group="Edit",
            shortcut="Enter",
            enabled="_enabled_inline_rename_active",
            run="_inline_rename_commit",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_INLINE_RENAME,
        ),
        ActionDef(
            id="editor.project_explorer.inline_rename.cancel",
            title="Cancel Inline Rename",
            keywords=(),
            group="Edit",
            shortcut="Escape",
            enabled="_enabled_inline_rename_active",
            run="_inline_rename_cancel",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_INLINE_RENAME,
        ),
        ActionDef(
            id="editor.project_explorer.inline_rename.backspace",
            title="Inline Rename Backspace",
            keywords=(),
            group="Edit",
            shortcut="Backspace",
            enabled="_enabled_inline_rename_active",
            run="_inline_rename_backspace",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_INLINE_RENAME,
        ),
        ActionDef(
            id="editor.project_explorer.inline_rename.delete",
            title="Inline Rename Delete",
            keywords=(),
            group="Edit",
            shortcut="Delete",
            enabled="_enabled_inline_rename_active",
            run="_inline_rename_delete",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_INLINE_RENAME,
        ),
        # --- Inline Rename Cursor Navigation Actions ---
        ActionDef(
            id="editor.project_explorer.inline_rename.cursor_left",
            title="Inline Rename Cursor Left",
            keywords=(),
            group="Edit",
            shortcut="Left",
            enabled="_enabled_inline_rename_active",
            run="_inline_rename_cursor_left",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_INLINE_RENAME,
        ),
        ActionDef(
            id="editor.project_explorer.inline_rename.cursor_left_extend",
            title="Inline Rename Cursor Left Extend",
            keywords=(),
            group="Edit",
            shortcut="Shift+Left",
            enabled="_enabled_inline_rename_active",
            run="_inline_rename_cursor_left_extend",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_INLINE_RENAME,
        ),
        ActionDef(
            id="editor.project_explorer.inline_rename.cursor_right",
            title="Inline Rename Cursor Right",
            keywords=(),
            group="Edit",
            shortcut="Right",
            enabled="_enabled_inline_rename_active",
            run="_inline_rename_cursor_right",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_INLINE_RENAME,
        ),
        ActionDef(
            id="editor.project_explorer.inline_rename.cursor_right_extend",
            title="Inline Rename Cursor Right Extend",
            keywords=(),
            group="Edit",
            shortcut="Shift+Right",
            enabled="_enabled_inline_rename_active",
            run="_inline_rename_cursor_right_extend",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_INLINE_RENAME,
        ),
        ActionDef(
            id="editor.project_explorer.inline_rename.cursor_home",
            title="Inline Rename Cursor Home",
            keywords=(),
            group="Edit",
            shortcut="Home",
            enabled="_enabled_inline_rename_active",
            run="_inline_rename_cursor_home",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_INLINE_RENAME,
        ),
        ActionDef(
            id="editor.project_explorer.inline_rename.cursor_home_extend",
            title="Inline Rename Cursor Home Extend",
            keywords=(),
            group="Edit",
            shortcut="Shift+Home",
            enabled="_enabled_inline_rename_active",
            run="_inline_rename_cursor_home_extend",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_INLINE_RENAME,
        ),
        ActionDef(
            id="editor.project_explorer.inline_rename.cursor_end",
            title="Inline Rename Cursor End",
            keywords=(),
            group="Edit",
            shortcut="End",
            enabled="_enabled_inline_rename_active",
            run="_inline_rename_cursor_end",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_INLINE_RENAME,
        ),
        ActionDef(
            id="editor.project_explorer.inline_rename.cursor_end_extend",
            title="Inline Rename Cursor End Extend",
            keywords=(),
            group="Edit",
            shortcut="Shift+End",
            enabled="_enabled_inline_rename_active",
            run="_inline_rename_cursor_end_extend",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_INLINE_RENAME,
        ),
        ActionDef(
            id="editor.project_explorer.inline_rename.cursor_word_left",
            title="Inline Rename Cursor Word Left",
            keywords=(),
            group="Edit",
            shortcut="Ctrl+Left",
            enabled="_enabled_inline_rename_active",
            run="_inline_rename_cursor_word_left",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_INLINE_RENAME,
        ),
        ActionDef(
            id="editor.project_explorer.inline_rename.cursor_word_left_extend",
            title="Inline Rename Cursor Word Left Extend",
            keywords=(),
            group="Edit",
            shortcut="Ctrl+Shift+Left",
            enabled="_enabled_inline_rename_active",
            run="_inline_rename_cursor_word_left_extend",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_INLINE_RENAME,
        ),
        ActionDef(
            id="editor.project_explorer.inline_rename.cursor_word_right",
            title="Inline Rename Cursor Word Right",
            keywords=(),
            group="Edit",
            shortcut="Ctrl+Right",
            enabled="_enabled_inline_rename_active",
            run="_inline_rename_cursor_word_right",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_INLINE_RENAME,
        ),
        ActionDef(
            id="editor.project_explorer.inline_rename.cursor_word_right_extend",
            title="Inline Rename Cursor Word Right Extend",
            keywords=(),
            group="Edit",
            shortcut="Ctrl+Shift+Right",
            enabled="_enabled_inline_rename_active",
            run="_inline_rename_cursor_word_right_extend",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_INLINE_RENAME,
        ),
        ActionDef(
            id="editor.project_explorer.inline_rename.delete_prev_word",
            title="Inline Rename Delete Prev Word",
            keywords=(),
            group="Edit",
            shortcut="Ctrl+Backspace",
            enabled="_enabled_inline_rename_active",
            run="_inline_rename_delete_prev_word",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_INLINE_RENAME,
        ),
        ActionDef(
            id="editor.project_explorer.inline_rename.delete_next_word",
            title="Inline Rename Delete Next Word",
            keywords=(),
            group="Edit",
            shortcut="Ctrl+Delete",
            enabled="_enabled_inline_rename_active",
            run="_inline_rename_delete_next_word",
            in_palette=False,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_INLINE_RENAME,
        ),
        ActionDef(
            id="editor.panel.outliner.toggle",
            title="Toggle Outliner",
            keywords=("panel", "outliner", "entities", "list"),
            group="View",
            shortcut="Ctrl+Alt+2",
            enabled="_enabled_always",
            run="_toggle_outliner_panel",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.panel.inspector.toggle",
            title="Toggle Inspector",
            keywords=("panel", "inspector", "properties", "details"),
            group="View",
            shortcut="Ctrl+Alt+1",
            enabled="_enabled_always",
            run="_toggle_inspector_panel",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.panel.history.toggle",
            title="Toggle History",
            keywords=("panel", "history", "undo", "stack"),
            group="View",
            shortcut="Ctrl+Alt+5",
            enabled="_enabled_always",
            run="_toggle_history_panel",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.panel.problems.toggle",
            title="Toggle Problems",
            keywords=("panel", "problems", "lint", "issues"),
            group="View",
            shortcut="Ctrl+Alt+3",
            enabled="_enabled_always",
            run="_toggle_problems_panel",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.problems.toggle",
            title="Toggle Problems (Alias)",
            keywords=("problems", "issues", "diagnostics"),
            group=None,
            shortcut="",
            enabled="_enabled_always",
            run="_toggle_problems_panel",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.panel.debug.toggle",
            title="Toggle Debug Tab",
            keywords=("panel", "debug", "events", "quests", "cutscenes"),
            group="View",
            shortcut="Ctrl+Alt+7",
            enabled="_enabled_always",
            run="_toggle_debug_panel",
            in_palette=True,
            in_menu=True,
            menu_label="Debug Tab",
        ),
        ActionDef(
            id="editor.debug.bundle.export",
            title="Export Debug Bundle...",
            keywords=("debug", "bundle", "export", "diagnostics"),
            group=None,
            shortcut="",
            enabled="_enabled_always",
            run="_action_debug_export_bundle",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.debug.copy.quest_diagnostic",
            title="Copy Selected Quest Diagnostic",
            keywords=("debug", "copy", "quest", "diagnostic", "clipboard"),
            group=None,
            shortcut="",
            enabled="_enabled_always",
            run="_action_debug_copy_quest_diagnostic",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.debug.copy.filtered_events",
            title="Copy Filtered Events",
            keywords=("debug", "copy", "events", "clipboard"),
            group=None,
            shortcut="",
            enabled="_enabled_always",
            run="_action_debug_copy_filtered_events",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.debug.copy.cutscene_summary",
            title="Copy Cutscene Summary",
            keywords=("debug", "copy", "cutscene", "clipboard"),
            group=None,
            shortcut="",
            enabled="_enabled_always",
            run="_action_debug_copy_cutscene_summary",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.debug.emit_feedback.info",
            title="Debug: Emit Feedback (Info)",
            keywords=("debug", "feedback", "toast", "info", "test"),
            group=None,
            shortcut="",
            enabled="_enabled_always",
            run="_action_debug_emit_feedback_info",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.debug.emit_feedback.warning",
            title="Debug: Emit Feedback (Warning)",
            keywords=("debug", "feedback", "toast", "warning", "test"),
            group=None,
            shortcut="",
            enabled="_enabled_always",
            run="_action_debug_emit_feedback_warning",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.debug.emit_feedback.error_sticky",
            title="Debug: Emit Feedback (Error Sticky)",
            keywords=("debug", "feedback", "toast", "error", "sticky", "test"),
            group=None,
            shortcut="",
            enabled="_enabled_always",
            run="_action_debug_emit_feedback_error_sticky",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.problems.jump_to_selected",
            title="Jump to Selected Problem",
            keywords=("jump", "problem", "go", "navigate", "location", "line"),
            group="View",
            shortcut="Enter",
            enabled="_enabled_problems_can_jump",
            run="_action_problems_jump",
            in_palette=True,
            in_menu=True,
            menu_label="Jump to Problem",
        ),
        ActionDef(
            id="editor.problems.jump_to_selected_ctrl",
            title="Jump to Selected Problem (Ctrl)",
            keywords=(),
            group="View",
            shortcut="Ctrl+Enter",
            enabled="_enabled_problems_can_jump",
            run="_action_problems_jump",
            in_palette=False,
            in_menu=False,
        ),
        ActionDef(
            id="editor.problems.copy_location",
            title="Copy Problem Location",
            keywords=("copy", "problem", "location", "line", "path", "clipboard"),
            group="View",
            shortcut="Ctrl+Shift+L",
            enabled="_enabled_problems_panel_active",
            run="_action_problems_copy_location",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.debug.event.select_entity",
            title="Debug: Select Event Entity",
            keywords=(),
            group=None,
            shortcut="",
            enabled="_enabled_always",
            run="_action_debug_select_event_entity",
            in_palette=False,
            in_menu=False,
        ),
        ActionDef(
            id="editor.panel.prefab_variant_editor.toggle",
            title="Toggle Prefab Variant Editor",
            keywords=("panel", "prefab", "variant", "overrides"),
            group="View",
            shortcut="Ctrl+Alt+6",
            enabled="_enabled_always",
            run="_toggle_prefab_variant_editor",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.find_everything.toggle",
            title="Find Everything",
            keywords=("find", "search", "launcher", "everything"),
            group="View",
            shortcut="Ctrl+K",
            enabled="_enabled_always",
            run="_toggle_find_everything",
            in_palette=False,
            in_menu=False,
        ),
        ActionDef(
            id="editor.scene_browser.open",
            title="Open Scene Browser",
            keywords=("scene", "browser", "open"),
            group="File",
            shortcut="Ctrl+Shift+O",
            enabled="_enabled_always",
            run="_open_scene_browser",
            in_palette=True,
            in_menu=True,
            menu_label="Open Scene...",
        ),
        ActionDef(
            id="editor.scene_switcher.toggle",
            title="Open Scene Switcher",
            keywords=("scene", "switcher", "open", "quick"),
            group="File",
            shortcut="Ctrl+O",
            enabled="_enabled_always",
            run="_toggle_scene_switcher",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.scene.save",
            title="Save Scene",
            keywords=("save", "scene"),
            group="File",
            shortcut="Ctrl+S",
            enabled="_enabled_scene_dirty",
            run="_save_scene",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.play.start",
            title="Play From Here",
            keywords=("play", "start", "test"),
            group=None,
            shortcut="F6",
            enabled="_enabled_always",
            run="_play_from_here",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.play.stop",
            title="Stop Playing",
            keywords=("stop", "play", "return"),
            group=None,
            shortcut="Esc",
            enabled="_enabled_play_session_active",
            run="_stop_playing",
            in_palette=True,
            in_menu=False,
            shortcut_scope=SHORTCUT_SCOPE_PLAYTEST,
        ),
        ActionDef(
            id="editor.build.windows",
            title="Build for Windows",
            keywords=("build", "windows", "deploy", "package", "player", "release"),
            group="File",
            shortcut="",
            enabled="_enabled_always",
            run="_build_windows",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.lighting_preset.1",
            title="Apply Lighting Preset 1",
            keywords=("lighting", "preset", "1"),
            group=None,
            shortcut="",
            enabled="_enabled_always",
            run="_action_apply_lighting_preset_0",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.lighting_preset.2",
            title="Apply Lighting Preset 2",
            keywords=("lighting", "preset", "2"),
            group=None,
            shortcut="",
            enabled="_enabled_always",
            run="_action_apply_lighting_preset_1",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.lighting_preset.3",
            title="Apply Lighting Preset 3",
            keywords=("lighting", "preset", "3"),
            group=None,
            shortcut="",
            enabled="_enabled_always",
            run="_action_apply_lighting_preset_2",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.lighting_preset.4",
            title="Apply Lighting Preset 4",
            keywords=("lighting", "preset", "4"),
            group=None,
            shortcut="",
            enabled="_enabled_always",
            run="_action_apply_lighting_preset_3",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="runtime.fog.toggle",
            title="Toggle Fog",
            keywords=("fog", "atmosphere"),
            group=None,
            shortcut="",
            enabled="_enabled_always",
            run="_toggle_fog",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="runtime.soft_shadows.toggle",
            title="Toggle Soft Shadows",
            keywords=("soft", "shadows", "lighting"),
            group=None,
            shortcut="",
            enabled="_enabled_always",
            run="_toggle_soft_shadows",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.asset_browser.toggle",
            title="Toggle Asset Browser",
            keywords=("asset", "browser", "view"),
            group="View",
            shortcut="Ctrl+Shift+A",
            enabled="_enabled_always",
            run="_toggle_asset_browser",
            in_palette=False,
            in_menu=True,
            menu_label="Asset Browser",
        ),
        ActionDef(
            id="editor.command_palette.toggle",
            title="Toggle Command Palette",
            keywords=("command", "palette"),
            group="View",
            shortcut="Ctrl+P",
            enabled="_enabled_always",
            run="_toggle_command_palette",
            in_palette=False,
            in_menu=True,
            menu_label="Command Palette",
        ),
        ActionDef(
            id="editor.keybinds.open",
            title="Preferences: Open Keyboard Shortcuts",
            keywords=("keybinds", "shortcuts", "mapping", "overrides", "keys"),
            group="Preferences",
            shortcut="Ctrl+Alt+K",
            enabled="_enabled_always",
            run="_open_keybinds",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.dock_left.toggle",
            title="Toggle Left Dock",
            keywords=("dock", "left", "toggle"),
            group="View",
            shortcut="Ctrl+L",
            enabled="_enabled_always",
            run="_toggle_left_dock",
            in_palette=False,
            in_menu=False,
        ),
        ActionDef(
            id="editor.dock_right.toggle",
            title="Toggle Right Dock",
            keywords=("dock", "right", "toggle"),
            group="View",
            shortcut="Ctrl+R",
            enabled="_enabled_right_dock_toggle",
            run="_toggle_right_dock",
            in_palette=False,
            in_menu=False,
        ),
        ActionDef(
            id="editor.viewport_maximize.toggle",
            title="Toggle Viewport Maximize",
            keywords=("viewport", "maximize", "toggle"),
            group="View",
            shortcut="Ctrl+Space",
            enabled="_enabled_always",
            run="_toggle_viewport_maximized",
            in_palette=False,
            in_menu=False,
        ),
        ActionDef(
            id="editor.scene_browser.toggle",
            title="Scene Browser",
            keywords=("scene", "browser", "view"),
            group="View",
            shortcut="",
            enabled="_enabled_always",
            run="_open_scene_browser",
            in_palette=False,
            in_menu=True,
            menu_label="Scene Browser",
        ),
        ActionDef(
            id="editor.ghost_originals.toggle",
            title="Toggle Ghost Originals",
            keywords=("ghost", "originals", "alt", "dup"),
            group="View",
            shortcut="",
            enabled="_enabled_always",
            run="_toggle_ghost_originals",
            in_palette=False,
            in_menu=True,
            menu_label="Ghost Originals During Alt-Dup",
        ),
        ActionDef(
            id="editor.prefab_palette.toggle",
            title="Prefab Palette",
            keywords=("prefab", "palette"),
            group="Scene",
            shortcut="P",
            enabled="_enabled_always",
            run="_toggle_prefab_palette",
            in_palette=False,
            in_menu=True,
            menu_label="Prefab Palette",
        ),
        ActionDef(
            id="editor.history.undo",
            title="Undo",
            keywords=("undo", "history"),
            group="Edit",
            shortcut="Ctrl+Z",
            enabled="_enabled_can_undo",
            run="_undo",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.history.redo",
            title="Redo",
            keywords=("redo", "history"),
            group="Edit",
            shortcut="Ctrl+Y",
            enabled="_enabled_can_redo",
            run="_redo",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.duplicate",
            title="Duplicate",
            keywords=("duplicate",),
            group="Edit",
            shortcut="Ctrl+D",
            enabled="_enabled_has_selection",
            run="_duplicate",
            in_palette=False,
            in_menu=True,
        ),
        ActionDef(
            id="editor.delete",
            title="Delete",
            keywords=("delete",),
            group="Edit",
            shortcut="Del",
            enabled="_enabled_has_selection_or_project_explorer",
            run="_delete",
            in_palette=False,
            in_menu=True,
        ),
        ActionDef(
            id="app.export_web_demo",
            title="Export Web Demo...",
            keywords=("export", "web", "demo"),
            group="File",
            shortcut="",
            enabled="_enabled_not_web",
            run="_export_web_demo",
            in_palette=False,
            in_menu=True,
        ),
        ActionDef(
            id="app.quit",
            title="Quit",
            keywords=("quit", "exit"),
            group="File",
            shortcut="Alt+F4",
            enabled="_enabled_not_web",
            run="_quit_app",
            in_palette=False,
            in_menu=True,
        ),
        ActionDef(
            id="editor.hd2d.preset.soft.apply",
            title="HD-2D Preset: Soft",
            keywords=("hd2d", "preset", "look", "soft", "style"),
            group="View",
            shortcut="",
            enabled="_enabled_scene_loaded",
            run="_action_apply_hd2d_preset_soft",
            in_palette=True,
            in_menu=True,
            menu_label="Soft",
        ),
        ActionDef(
            id="editor.hd2d.preset.crisp.apply",
            title="HD-2D Preset: Crisp",
            keywords=("hd2d", "preset", "look", "crisp", "style"),
            group="View",
            shortcut="",
            enabled="_enabled_scene_loaded",
            run="_action_apply_hd2d_preset_crisp",
            in_palette=True,
            in_menu=True,
            menu_label="Crisp",
        ),
        ActionDef(
            id="editor.hd2d.preset.noir.apply",
            title="HD-2D Preset: Noir",
            keywords=("hd2d", "preset", "look", "noir", "style"),
            group="View",
            shortcut="",
            enabled="_enabled_scene_loaded",
            run="_action_apply_hd2d_preset_noir",
            in_palette=True,
            in_menu=True,
            menu_label="Noir",
        ),
        ActionDef(
            id="editor.hd2d.preset.dreamy.apply",
            title="HD-2D Preset: Dreamy",
            keywords=("hd2d", "preset", "look", "dreamy", "style"),
            group="View",
            shortcut="",
            enabled="_enabled_scene_loaded",
            run="_action_apply_hd2d_preset_dreamy",
            in_palette=True,
            in_menu=True,
            menu_label="Dreamy",
        ),
        ActionDef(
            id="editor.hd2d.defaults.upgrade_scene",
            title="Upgrade Scene to HD2D Defaults",
            keywords=("hd2d", "defaults", "upgrade", "scene", "style"),
            group="View",
            shortcut="",
            enabled="_enabled_scene_loaded",
            run="_upgrade_scene_to_hd2d_defaults",
            in_palette=True,
            in_menu=False,
        ),
        # HD-2D Settings Panel toggle actions
        ActionDef(
            id="editor.hd2d.toggle.shadows",
            title="HD-2D: Toggle Shadows",
            keywords=("hd2d", "shadows", "toggle", "setting"),
            group="View",
            shortcut="",
            enabled="_enabled_scene_loaded",
            run="_action_toggle_hd2d_shadows_enabled",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.hd2d.toggle.shadows_contact",
            title="HD-2D: Toggle Contact Shadows",
            keywords=("hd2d", "shadows", "contact", "toggle", "setting"),
            group="View",
            shortcut="",
            enabled="_enabled_scene_loaded",
            run="_action_toggle_hd2d_shadows_contact_enabled",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.hd2d.toggle.shadows_ao",
            title="HD-2D: Toggle Ambient Occlusion",
            keywords=("hd2d", "shadows", "ao", "ambient", "occlusion", "toggle", "setting"),
            group="View",
            shortcut="",
            enabled="_enabled_scene_loaded",
            run="_action_toggle_hd2d_shadows_ao_enabled",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.hd2d.toggle.depth_tint",
            title="HD-2D: Toggle Depth Tint",
            keywords=("hd2d", "tint", "depth", "toggle", "setting"),
            group="View",
            shortcut="",
            enabled="_enabled_scene_loaded",
            run="_action_toggle_hd2d_depth_tint_enabled",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.hd2d.toggle.outline",
            title="HD-2D: Toggle Outline",
            keywords=("hd2d", "outline", "toggle", "setting"),
            group="View",
            shortcut="",
            enabled="_enabled_scene_loaded",
            run="_action_toggle_hd2d_outline_enabled",
            in_palette=True,
            in_menu=False,
        ),
        # HD-2D Settings Panel slider actions (increase/decrease)
        ActionDef(
            id="editor.hd2d.tint_strength.increase",
            title="HD-2D: Increase Tint Strength",
            keywords=("hd2d", "tint", "strength", "increase"),
            group="View",
            shortcut="",
            enabled="_enabled_scene_loaded",
            run="_action_adjust_hd2d_depth_tint_strength_up",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.hd2d.tint_strength.decrease",
            title="HD-2D: Decrease Tint Strength",
            keywords=("hd2d", "tint", "strength", "decrease"),
            group="View",
            shortcut="",
            enabled="_enabled_scene_loaded",
            run="_action_adjust_hd2d_depth_tint_strength_down",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.hd2d.outline_strength.increase",
            title="HD-2D: Increase Outline Strength",
            keywords=("hd2d", "outline", "strength", "increase"),
            group="View",
            shortcut="",
            enabled="_enabled_scene_loaded",
            run="_action_adjust_hd2d_outline_strength_up",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.hd2d.outline_strength.decrease",
            title="HD-2D: Decrease Outline Strength",
            keywords=("hd2d", "outline", "strength", "decrease"),
            group="View",
            shortcut="",
            enabled="_enabled_scene_loaded",
            run="_action_adjust_hd2d_outline_strength_down",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.hd2d.outline_radius.increase",
            title="HD-2D: Increase Outline Radius",
            keywords=("hd2d", "outline", "radius", "increase"),
            group="View",
            shortcut="",
            enabled="_enabled_scene_loaded",
            run="_action_adjust_hd2d_outline_radius_up",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.hd2d.outline_radius.decrease",
            title="HD-2D: Decrease Outline Radius",
            keywords=("hd2d", "outline", "radius", "decrease"),
            group="View",
            shortcut="",
            enabled="_enabled_scene_loaded",
            run="_action_adjust_hd2d_outline_radius_down",
            in_palette=True,
            in_menu=False,
        ),
        # HD-2D Entity Override toggle actions (when entity is selected)
        ActionDef(
            id="editor.entity.hd2d.toggle.shadow",
            title="Entity HD-2D: Toggle Shadow Override",
            keywords=("entity", "hd2d", "shadow", "toggle", "override"),
            group="Entity",
            shortcut="",
            enabled="_enabled_entity_selected",
            run="_action_toggle_entity_shadow_enabled",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.entity.hd2d.toggle.shadow_contact",
            title="Entity HD-2D: Toggle Contact Shadow Override",
            keywords=("entity", "hd2d", "shadow", "contact", "toggle", "override"),
            group="Entity",
            shortcut="",
            enabled="_enabled_entity_selected",
            run="_action_toggle_entity_shadow_contact_enabled",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.entity.hd2d.toggle.shadow_ao",
            title="Entity HD-2D: Toggle AO Shadow Override",
            keywords=("entity", "hd2d", "shadow", "ao", "ambient", "occlusion", "toggle", "override"),
            group="Entity",
            shortcut="",
            enabled="_enabled_entity_selected",
            run="_action_toggle_entity_shadow_ao_enabled",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.entity.hd2d.toggle.depth_tint",
            title="Entity HD-2D: Toggle Depth Tint Override",
            keywords=("entity", "hd2d", "tint", "depth", "toggle", "override"),
            group="Entity",
            shortcut="",
            enabled="_enabled_entity_selected",
            run="_action_toggle_entity_depth_tint_enabled",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.entity.hd2d.toggle.outline",
            title="Entity HD-2D: Toggle Outline Override",
            keywords=("entity", "hd2d", "outline", "toggle", "override"),
            group="Entity",
            shortcut="",
            enabled="_enabled_entity_selected",
            run="_action_toggle_entity_outline_enabled",
            in_palette=True,
            in_menu=False,
        ),
        # HD-2D Entity Override slider actions
        ActionDef(
            id="editor.entity.hd2d.tint_strength.increase",
            title="Entity HD-2D: Increase Tint Strength Override",
            keywords=("entity", "hd2d", "tint", "strength", "increase", "override"),
            group="Entity",
            shortcut="",
            enabled="_enabled_entity_selected",
            run="_action_adjust_entity_depth_tint_strength_up",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.entity.hd2d.tint_strength.decrease",
            title="Entity HD-2D: Decrease Tint Strength Override",
            keywords=("entity", "hd2d", "tint", "strength", "decrease", "override"),
            group="Entity",
            shortcut="",
            enabled="_enabled_entity_selected",
            run="_action_adjust_entity_depth_tint_strength_down",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.entity.hd2d.outline_strength.increase",
            title="Entity HD-2D: Increase Outline Strength Override",
            keywords=("entity", "hd2d", "outline", "strength", "increase", "override"),
            group="Entity",
            shortcut="",
            enabled="_enabled_entity_selected",
            run="_action_adjust_entity_outline_strength_up",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.entity.hd2d.outline_strength.decrease",
            title="Entity HD-2D: Decrease Outline Strength Override",
            keywords=("entity", "hd2d", "outline", "strength", "decrease", "override"),
            group="Entity",
            shortcut="",
            enabled="_enabled_entity_selected",
            run="_action_adjust_entity_outline_strength_down",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.entity.hd2d.outline_radius.increase",
            title="Entity HD-2D: Increase Outline Radius Override",
            keywords=("entity", "hd2d", "outline", "radius", "increase", "override"),
            group="Entity",
            shortcut="",
            enabled="_enabled_entity_selected",
            run="_action_adjust_entity_outline_radius_up",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.entity.hd2d.outline_radius.decrease",
            title="Entity HD-2D: Decrease Outline Radius Override",
            keywords=("entity", "hd2d", "outline", "radius", "decrease", "override"),
            group="Entity",
            shortcut="",
            enabled="_enabled_entity_selected",
            run="_action_adjust_entity_outline_radius_down",
            in_palette=True,
            in_menu=False,
        ),
        # HD-2D Entity Override clipboard actions (copy/paste/clear)
        ActionDef(
            id="editor.hd2d.entity_overrides.copy",
            title="Entity HD-2D: Copy Overrides",
            keywords=("entity", "hd2d", "override", "copy", "clipboard"),
            group="Entity",
            shortcut="Ctrl+Alt+C",
            enabled="_enabled_entity_selected",
            run="_copy_entity_hd2d_overrides",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.hd2d.entity_overrides.paste",
            title="Entity HD-2D: Paste Overrides (Merge)",
            keywords=("entity", "hd2d", "override", "paste", "clipboard", "merge"),
            group="Entity",
            shortcut="Ctrl+Alt+V",
            enabled="_enabled_hd2d_clipboard_has_data",
            run="_paste_entity_hd2d_overrides",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.hd2d.entity_overrides.paste_replace",
            title="Entity HD-2D: Paste Overrides (Replace)",
            keywords=("entity", "hd2d", "override", "paste", "clipboard", "replace"),
            group="Entity",
            shortcut="Ctrl+Shift+Alt+V",
            enabled="_enabled_hd2d_clipboard_has_data",
            run="_paste_replace_entity_hd2d_overrides",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.hd2d.entity_overrides.clear_all",
            title="Entity HD-2D: Clear All Overrides",
            keywords=("entity", "hd2d", "override", "clear", "all", "reset"),
            group="Entity",
            shortcut="Ctrl+Shift+Backspace",
            enabled="_enabled_entity_has_overrides",
            run="_clear_all_entity_hd2d_overrides",
            in_palette=True,
            in_menu=False,
        ),
        # HD-2D Entity Override batch actions
        ActionDef(
            id="editor.hd2d.entity_overrides.batch_paste_radius_merge",
            title="Entity HD-2D: Batch Paste Overrides (Radius, Merge)",
            keywords=("entity", "hd2d", "override", "batch", "paste", "radius", "merge", "nearby"),
            group="Entity",
            shortcut="Ctrl+Shift+B",
            enabled="_enabled_hd2d_clipboard_has_data",
            run="_batch_paste_hd2d_overrides_merge",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.hd2d.entity_overrides.batch_paste_radius_replace",
            title="Entity HD-2D: Batch Paste Overrides (Radius, Replace)",
            keywords=("entity", "hd2d", "override", "batch", "paste", "radius", "replace", "nearby"),
            group="Entity",
            shortcut="Ctrl+Shift+Alt+B",
            enabled="_enabled_hd2d_clipboard_has_data",
            run="_batch_paste_hd2d_overrides_replace",
            in_palette=True,
            in_menu=False,
        ),
        # HD-2D batch radius adjustment actions
        ActionDef(
            id="editor.hd2d.entity_overrides.batch_radius.increase",
            title="Entity HD-2D: Increase Batch Radius (+16px)",
            keywords=("entity", "hd2d", "batch", "radius", "increase", "expand"),
            group="Entity",
            shortcut="Ctrl+Alt+]",
            enabled="_enabled_always",
            run="_action_adjust_hd2d_batch_radius_up",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.hd2d.entity_overrides.batch_radius.decrease",
            title="Entity HD-2D: Decrease Batch Radius (-16px)",
            keywords=("entity", "hd2d", "batch", "radius", "decrease", "shrink"),
            group="Entity",
            shortcut="Ctrl+Alt+[",
            enabled="_enabled_always",
            run="_action_adjust_hd2d_batch_radius_down",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.hd2d.entity_overrides.batch_radius.reset",
            title="Entity HD-2D: Reset Batch Radius (96px)",
            keywords=("entity", "hd2d", "batch", "radius", "reset", "default"),
            group="Entity",
            shortcut="Ctrl+Alt+\\\\",
            enabled="_enabled_always",
            run="_reset_hd2d_batch_radius",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.background_planes.add",
            title="Background Planes: Add",
            keywords=("background", "plane", "planes", "parallax", "add"),
            group="Scene",
            shortcut="Ctrl+Alt+B",
            enabled="_enabled_always",
            run="_action_planes_add",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.background_planes.duplicate",
            title="Background Planes: Duplicate Selected",
            keywords=("background", "plane", "planes", "parallax", "duplicate", "copy"),
            group="Scene",
            shortcut="Ctrl+Alt+D",
            enabled="_enabled_plane_selected",
            run="_action_planes_duplicate",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.background_planes.remove",
            title="Background Planes: Remove Selected",
            keywords=("background", "plane", "planes", "parallax", "remove", "delete"),
            group="Scene",
            shortcut="Ctrl+Alt+Backspace",
            enabled="_enabled_plane_selected",
            run="_action_planes_remove",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.background_planes.move_up",
            title="Background Planes: Move Up",
            keywords=("background", "plane", "planes", "parallax", "move", "up", "layer"),
            group="Scene",
            shortcut="Alt+PageUp",
            enabled="_enabled_plane_selected",
            run="_action_planes_move_up",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.background_planes.move_down",
            title="Background Planes: Move Down",
            keywords=("background", "plane", "planes", "parallax", "move", "down", "layer"),
            group="Scene",
            shortcut="Alt+PageDown",
            enabled="_enabled_plane_selected",
            run="_action_planes_move_down",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.background_planes.move_top",
            title="Background Planes: Move To Top",
            keywords=("background", "plane", "planes", "parallax", "move", "top", "first", "layer"),
            group="Scene",
            shortcut="",
            enabled="_enabled_plane_selected",
            run="_action_planes_move_top",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.background_planes.move_bottom",
            title="Background Planes: Move To Bottom",
            keywords=("background", "plane", "planes", "parallax", "move", "bottom", "last", "layer"),
            group="Scene",
            shortcut="",
            enabled="_enabled_plane_selected",
            run="_action_planes_move_bottom",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.background_planes.move_to_index",
            title="Background Planes: Move To Index",
            keywords=("background", "plane", "planes", "parallax", "move", "index", "position"),
            group="Scene",
            shortcut="",
            enabled="_enabled_plane_selected",
            run="_action_planes_move_to_index",
            in_palette=True,
            in_menu=False,
        ),
        ActionDef(
            id="editor.background_planes.select_prev",
            title="Background Planes: Select Previous",
            keywords=("background", "plane", "planes", "parallax", "select", "previous", "cycle"),
            group="Scene",
            shortcut="Ctrl+Alt+PageUp",
            enabled="_enabled_planes_exist",
            run="_action_planes_select_prev",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.background_planes.select_next",
            title="Background Planes: Select Next",
            keywords=("background", "plane", "planes", "parallax", "select", "next", "cycle"),
            group="Scene",
            shortcut="Ctrl+Alt+PageDown",
            enabled="_enabled_planes_exist",
            run="_action_planes_select_next",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.background_planes.toggle_repeat_x",
            title="Background Planes: Toggle Tiling X",
            keywords=("background", "plane", "planes", "parallax", "tiling", "tile", "repeat", "x"),
            group="Scene",
            shortcut="Ctrl+Alt+X",
            enabled="_enabled_plane_selected",
            run="_action_planes_toggle_repeat_x",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.background_planes.toggle_repeat_y",
            title="Background Planes: Toggle Tiling Y",
            keywords=("background", "plane", "planes", "parallax", "tiling", "tile", "repeat", "y"),
            group="Scene",
            shortcut="Ctrl+Alt+Y",
            enabled="_enabled_plane_selected",
            run="_action_planes_toggle_repeat_y",
            in_palette=True,
            in_menu=True,
        ),
        # -------------------------------------------------------------------------
        # Align / Distribute (Multi-Select)
        # Use Ctrl+Shift+Alt to avoid conflicts with HD2D and Problems shortcuts
        # -------------------------------------------------------------------------
        ActionDef(
            id="editor.align.left",
            title="Align Left",
            keywords=("align", "left", "edge", "multiselect", "arrange"),
            group="Arrange",
            shortcut="Ctrl+Shift+Alt+L",
            enabled="_enabled_multiselect",
            run="_action_align_left",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.align.right",
            title="Align Right",
            keywords=("align", "right", "edge", "multiselect", "arrange"),
            group="Arrange",
            shortcut="Ctrl+Shift+Alt+R",
            enabled="_enabled_multiselect",
            run="_action_align_right",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.align.top",
            title="Align Top",
            keywords=("align", "top", "edge", "multiselect", "arrange"),
            group="Arrange",
            shortcut="Ctrl+Shift+Alt+T",
            enabled="_enabled_multiselect",
            run="_action_align_top",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.align.bottom",
            title="Align Bottom",
            keywords=("align", "bottom", "edge", "multiselect", "arrange"),
            group="Arrange",
            shortcut="Ctrl+Shift+Alt+O",
            enabled="_enabled_multiselect",
            run="_action_align_bottom",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.align.center_horizontal",
            title="Align Center Horizontal",
            keywords=("align", "center", "horizontal", "multiselect", "arrange"),
            group="Arrange",
            shortcut="Ctrl+Shift+Alt+H",
            enabled="_enabled_multiselect",
            run="_action_align_center_horizontal",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.align.center_vertical",
            title="Align Center Vertical",
            keywords=("align", "center", "vertical", "multiselect", "arrange"),
            group="Arrange",
            shortcut="Ctrl+Shift+Alt+M",
            enabled="_enabled_multiselect",
            run="_action_align_center_vertical",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.distribute.horizontal",
            title="Distribute Horizontal",
            keywords=("distribute", "horizontal", "space", "even", "multiselect", "arrange"),
            group="Arrange",
            shortcut="Ctrl+Shift+Alt+D",
            enabled="_enabled_multiselect_3",
            run="_action_distribute_horizontal",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.distribute.vertical",
            title="Distribute Vertical",
            keywords=("distribute", "vertical", "space", "even", "multiselect", "arrange"),
            group="Arrange",
            shortcut="Ctrl+Shift+Alt+E",
            enabled="_enabled_multiselect_3",
            run="_action_distribute_vertical",
            in_palette=True,
            in_menu=True,
        ),
        ActionDef(
            id="editor.tour.start",
            title="Start Editor Tour",
            keywords=("tour", "help", "welcome", "intro", "guide", "walkthrough"),
            group="Help",
            shortcut="",
            enabled="_enabled_always",
            run="_start_tour",
            in_palette=True,
            in_menu=False,
        ),
)
