"""Protocols for editor controller satellites.

Defines the interface contracts that the main EditorController must implement
to support its delegated satellite controllers (Diet Architecture).
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

@runtime_checkable
class EditorFileOpsProtocol(Protocol):
    """Protocol for file operations controller."""
    def copy_selected_path(self) -> bool: ...
    def safe_rename_selected_asset(self, new_name: str) -> bool: ...
    def can_copy_selected_path(self) -> bool: ...
    def can_safe_rename_selected_asset(self) -> bool: ...
    def can_safe_move_selected_asset(self) -> bool: ...

@runtime_checkable
class EditorHostProtocol(Protocol):
    """Protocol for the main EditorController host."""
    
    @property
    def file_ops(self) -> EditorFileOpsProtocol: ...
    
    # State access
    window: Any
    scene_switcher_recent: Any
    # ... extensible ...

@runtime_checkable
class EditorUiFlowHost(Protocol):
    """Protocol for the host of EditorUiFlowController."""
    
    # Core Actions
    def ui_activate_command(self, cmd_id: str) -> bool: ...
    def ui_activate_scene(self, scene_id: str) -> bool: ...
    def ui_activate_asset(self, asset_id: str) -> bool: ...
    def ui_activate_entity(self, entity_id: str) -> bool: ...
    def ui_activate_problem(self, problem_id: str) -> bool: ...
    
    def ui_get_palette_items(self) -> list[Any]: ...
    def ui_toast(self, msg: str) -> None: ...
    
    # HD2D Preview
    def ui_hd2d_preview(self, preset_id: str) -> None: ...
    def ui_hd2d_cancel_preview(self) -> None: ...
    def ui_hd2d_commit(self, preset_id: str) -> bool: ...
