import argparse
from typing import Callable, cast

from . import backgrounds, entities, macro, ops, prefab_overrides, stamp, tilemap


def register(subparsers: argparse._SubParsersAction) -> None:
    # New Scene
    p_new = subparsers.add_parser("new-scene", help="Create a new scene", description="Create a new scene")
    p_new.add_argument("name", help="Scene name")
    p_new.add_argument("--template", default="empty", help="Scene template")
    p_new.add_argument("--encounter-layout", choices=["standard", "bossed", "gauntlet"], help="Encounter layout preset")
    p_new.set_defaults(func=ops._handle_new_scene)

    # Edit Scene
    p_edit = subparsers.add_parser("edit-scene", help="Edit scene properties", description="Edit scene properties")
    p_edit.add_argument("path", help="Path to scene file")
    p_edit.add_argument("--budget", type=float, help="Set encounter budget")
    p_edit.add_argument("--elite-cap", type=int, help="Set elite cap")
    p_edit.add_argument("--allow-elites", choices=["true", "false"], help="Set allow elites")
    p_edit.add_argument("--boss-reserve", type=float, help="Set boss budget reserve")
    p_edit.add_argument("--add-transition", help="Target scene for new transition")
    p_edit.add_argument("--at", help="Coordinates x,y")
    p_edit.add_argument("--spawn-id", help="Spawn ID in target scene")
    p_edit.set_defaults(func=ops._handle_edit_scene)

    # Tidy Scene
    p_tidy = subparsers.add_parser("tidy-scene", help="Format and compact scene file", description="Format and compact scene file")
    p_tidy.add_argument("scene_path", help="Path to scene file")
    p_tidy.set_defaults(func=ops._handle_tidy_scene)

    # List Scenes
    p_list = subparsers.add_parser("list-scenes", help="List all scenes in the project", description="List all scenes in the project")
    p_list.add_argument("--out", help="Optional path to write JSON output")
    p_list.set_defaults(func=ops._handle_list_scenes)

    # Validate (Single Scene)
    p_val = subparsers.add_parser("validate", help="Validate a scene", description="Validate a scene")
    p_val.add_argument("scene_path", help="Path to scene file")
    p_val.set_defaults(func=ops._handle_validate_scene_file)

    # --- Grouped authoring commands ---

    p_scene = subparsers.add_parser("scene", help="Scene authoring commands")
    scene_subs = p_scene.add_subparsers(dest="scene_command", required=True)

    p_create = scene_subs.add_parser("create", help="Create a scene file (idempotent)")
    p_create.add_argument("scene_path", help="Path to scene JSON")
    p_create.add_argument("--width", type=int, required=True, help="Tilemap width in tiles")
    p_create.add_argument("--height", type=int, required=True, help="Tilemap height in tiles")
    p_create.add_argument("--tile-w", dest="tile_w", type=int, required=True, help="Tile width")
    p_create.add_argument("--tile-h", dest="tile_h", type=int, required=True, help="Tile height")
    p_create.add_argument("--layer", action="append", default=[], help="Layer spec id:z[:parallax] (repeatable)")
    p_create.add_argument("--collision-layer", dest="collision_layer", help="Optional collision layer id")
    p_create.add_argument("--bg", action="append", default=[], help="Background spec id:path:z:parallax[:repeatx][:repeaty]")
    p_create.add_argument("--spawn", action="append", default=[], help="Spawn spec spawn_id:x:y (repeatable)")
    p_create.set_defaults(func=ops._handle_scene_create)

    p_scene_val_bg = scene_subs.add_parser("validate-backgrounds", help="Validate background_layers in a scene")
    p_scene_val_bg.add_argument("scene_path", help="Path to scene JSON")
    p_scene_val_bg.set_defaults(func=backgrounds._handle_scene_validate_backgrounds)

    # scene tilemap
    p_tilemap = scene_subs.add_parser("tilemap", help="Manage scene tilemaps")
    tm_subs = p_tilemap.add_subparsers(dest="tilemap_command", required=True)

    p_tm_add = tm_subs.add_parser("add-layer", help="Add a tilemap layer")
    p_tm_add.add_argument("scene_path", help="Path to scene JSON")
    p_tm_add.add_argument("--id", required=True, help="Layer ID")
    p_tm_add.add_argument("--z", type=int, required=True, help="Z index")
    p_tm_add.add_argument("--parallax", type=float, default=1.0, help="Parallax factor")
    p_tm_add.add_argument("--collision", action="store_true", help="Set collision_layer_id to this layer")
    p_tm_add.set_defaults(func=tilemap._handle_scene_tilemap_add_layer)

    p_tm_rem = tm_subs.add_parser("remove-layer", help="Remove a tilemap layer")
    p_tm_rem.add_argument("scene_path", help="Path to scene JSON")
    p_tm_rem.add_argument("--id", required=True, help="Layer ID")
    p_tm_rem.set_defaults(func=tilemap._handle_scene_tilemap_remove_layer)

    p_tm_init = tm_subs.add_parser("init", help="Initialize tilemap")
    p_tm_init.add_argument("scene_path", help="Path to scene JSON")
    p_tm_init.add_argument("--width", type=int, required=True, help="Width in tiles")
    p_tm_init.add_argument("--height", type=int, required=True, help="Height in tiles")
    p_tm_init.add_argument("--tile-w", dest="tile_w", type=int, required=True, help="Tile width")
    p_tm_init.add_argument("--tile-h", dest="tile_h", type=int, required=True, help="Tile height")
    p_tm_init.add_argument("--layer", action="append", default=[], help="Layer spec id:z[:parallax] (repeatable)")
    p_tm_init.add_argument("--collision-layer", dest="collision_layer", help="Optional collision layer id")
    p_tm_init.add_argument("--fill", action="append", default=[], help="Fill spec layer_id:tile (repeatable)")
    p_tm_init.set_defaults(func=tilemap._handle_scene_tilemap_init)

    p_tm_resize = tm_subs.add_parser("resize", help="Resize tilemap grid")
    p_tm_resize.add_argument("scene_path", help="Path to scene JSON")
    p_tm_resize.add_argument("--width", type=int, required=True, help="New width in tiles")
    p_tm_resize.add_argument("--height", type=int, required=True, help="New height in tiles")
    p_tm_resize.add_argument("--anchor", default="tl", choices=["tl", "tr", "bl", "br"], help="Resize anchor")
    p_tm_resize.add_argument("--fill-tile", dest="fill_tile", type=int, default=0, help="Fill tile id for new cells")
    p_tm_resize.add_argument("--only-layer", dest="only_layer", action="append", default=[], help="Resize only this layer id (repeatable)")
    p_tm_resize.set_defaults(func=tilemap._handle_scene_tilemap_resize)

    p_tm_fill = tm_subs.add_parser("flood-fill", help="Flood fill tilemap")
    p_tm_fill.add_argument("scene_path", help="Path to scene JSON")
    p_tm_fill.add_argument("--layer-id", required=True, help="Layer ID")
    p_tm_fill.add_argument("--x", type=int, required=True, help="X coord")
    p_tm_fill.add_argument("--y", type=int, required=True, help="Y coord")
    p_tm_fill.add_argument("--tile", type=int, required=True, help="New tile id")
    p_tm_fill.add_argument("--target", type=int, help="Target tile id (default: infer from x,y)")
    p_tm_fill.add_argument("--max-tiles", dest="max_tiles", type=int, help="Max tiles to fill (default: 5000)")
    p_tm_fill.add_argument("--diag", action="store_true", help="Use 8-neighbor fill")
    p_tm_fill.add_argument("--clip", action="store_true", help="Clip fill at max-tiles instead of error")
    p_tm_fill.set_defaults(func=tilemap._handle_scene_tilemap_flood_fill)

    p_tm_rect = tm_subs.add_parser("fill-rect", help="Fill rectangle on tilemap (inclusive coords)")
    p_tm_rect.add_argument("scene_path", help="Path to scene JSON")
    p_tm_rect.add_argument("--layer-id", required=True, help="Layer ID")
    p_tm_rect.add_argument("--x0", type=int, required=True, help="X0 (inclusive)")
    p_tm_rect.add_argument("--y0", type=int, required=True, help="Y0 (inclusive)")
    p_tm_rect.add_argument("--x1", type=int, required=True, help="X1 (inclusive)")
    p_tm_rect.add_argument("--y1", type=int, required=True, help="Y1 (inclusive)")
    p_tm_rect.add_argument("--tile", type=int, required=True, help="Tile id")
    p_tm_rect.set_defaults(func=tilemap._handle_scene_tilemap_fill_rect)

    p_tm_clear = tm_subs.add_parser("clear-rect", help="Clear rectangle on tilemap (inclusive coords)")
    p_tm_clear.add_argument("scene_path", help="Path to scene JSON")
    p_tm_clear.add_argument("--layer-id", required=True, help="Layer ID")
    p_tm_clear.add_argument("--x0", type=int, required=True, help="X0 (inclusive)")
    p_tm_clear.add_argument("--y0", type=int, required=True, help="Y0 (inclusive)")
    p_tm_clear.add_argument("--x1", type=int, required=True, help="X1 (inclusive)")
    p_tm_clear.add_argument("--y1", type=int, required=True, help="Y1 (inclusive)")
    p_tm_clear.set_defaults(func=tilemap._handle_scene_tilemap_clear_rect)

    p_tm_paint = tm_subs.add_parser("paint", help="Paint a single tile")
    p_tm_paint.add_argument("scene_path", help="Path to scene JSON")
    p_tm_paint.add_argument("--layer-id", required=True, help="Layer ID")
    p_tm_paint.add_argument("--x", type=int, required=True, help="X coord")
    p_tm_paint.add_argument("--y", type=int, required=True, help="Y coord")
    p_tm_paint.add_argument("--tile", type=int, required=True, help="Tile id")
    p_tm_paint.set_defaults(func=tilemap._handle_scene_tilemap_paint)

    p_tm_brush = tm_subs.add_parser("brush", help="Apply a brush to a tilemap layer")
    p_tm_brush.add_argument("scene_path", help="Path to scene JSON")
    p_tm_brush.add_argument("--layer-id", required=True, help="Layer ID")
    p_tm_brush.add_argument("--brush", required=True, help="Brush JSON path")
    p_tm_brush.add_argument("--x", type=int, required=True, help="X coord")
    p_tm_brush.add_argument("--y", type=int, required=True, help="Y coord")
    p_tm_brush.add_argument("--anchor", default="tl", choices=["tl", "tr", "bl", "br"], help="Brush anchor")
    p_tm_brush.add_argument("--clip", action="store_true", help="Clip brush placement to bounds")
    p_tm_brush.set_defaults(func=tilemap._handle_scene_tilemap_brush)

    # scene backgrounds
    p_bg = scene_subs.add_parser("backgrounds", help="Manage background layers in a scene")
    bg_subs = p_bg.add_subparsers(dest="backgrounds_command", required=True)

    p_bg_add = bg_subs.add_parser("add-layer", help="Add/update a background layer")
    p_bg_add.add_argument("scene_path", help="Path to scene JSON")
    p_bg_add.add_argument("--id", required=True, help="Layer ID")
    p_bg_add.add_argument("--path", required=True, help="Texture path")
    p_bg_add.add_argument("--z", type=int, required=True, help="Z index")
    p_bg_add.add_argument("--parallax", type=float, default=1.0, help="Parallax factor")
    p_bg_add.add_argument("--repeat-x", action="store_true", help="Repeat X")
    p_bg_add.add_argument("--repeat-y", action="store_true", help="Repeat Y")
    p_bg_add.set_defaults(func=backgrounds._handle_scene_backgrounds_add_layer)

    p_bg_rem = bg_subs.add_parser("remove-layer", help="Remove a background layer")
    p_bg_rem.add_argument("scene_path", help="Path to scene JSON")
    p_bg_rem.add_argument("--id", required=True, help="Layer ID")
    p_bg_rem.set_defaults(func=backgrounds._handle_scene_backgrounds_remove_layer)

    p_ph = scene_subs.add_parser("add-placeholder", help="Add a theme_enemy_placeholder entity")
    p_ph.add_argument("scene_path", help="Path to scene JSON")
    p_ph.add_argument("--x", type=float, required=True, help="X position")
    p_ph.add_argument("--y", type=float, required=True, help="Y position")
    p_ph.add_argument("--id", help="Entity ID (optional)")
    p_ph.set_defaults(func=entities._handle_scene_add_placeholder)

    p_ent = scene_subs.add_parser("add-entity", help="Add/update a prefab-backed entity")
    p_ent.add_argument("scene_path", help="Path to scene JSON")
    p_ent.add_argument("--prefab-id", required=True, dest="prefab_id", help="Prefab ID")
    p_ent.add_argument("--x", type=float, required=True, help="X position")
    p_ent.add_argument("--y", type=float, required=True, help="Y position")
    p_ent.add_argument("--id", help="Entity ID (optional)")
    p_ent.add_argument("--name", help="Entity name (optional)")
    p_ent.add_argument("--layer", help="Layer name (optional)")
    p_ent.add_argument("--tags", action="append", default=[], help="Tags (repeatable)")
    p_ent.add_argument("--behaviour", action="append", default=[], help="Behaviour name (repeatable)")
    p_ent.add_argument("--behaviour-json", action="append", default=[], help="Behaviour config Name=<json> (repeatable)")
    p_ent.set_defaults(func=entities._handle_scene_add_entity)

    p_trig = scene_subs.add_parser("add-triggerzone-objective", help="Insert TriggerZone + SetGameStateOnEvent pair")
    p_trig.add_argument("scene_path", help="Path to scene JSON")
    p_trig.add_argument("--x", type=float, required=True, help="X position")
    p_trig.add_argument("--y", type=float, required=True, help="Y position")
    p_trig.add_argument("--radius", type=float, required=True, help="Trigger radius")
    p_trig.add_argument("--zone-id", required=True, dest="zone_id", help="Zone ID")
    p_trig.add_argument("--set-flag", required=True, dest="set_flag", help="Flag to set true")
    p_trig.add_argument("--require", action="append", default=[], help="Required flags (repeatable)")
    p_trig.add_argument("--forbid", action="append", default=[], help="Forbidden flags (repeatable)")
    p_trig.add_argument("--toast", help="Toast message")
    p_trig.add_argument("--toast-seconds", type=float, dest="toast_seconds", help="Toast duration (seconds)")
    p_trig.set_defaults(func=entities._handle_scene_add_triggerzone_objective)

    p_dial = scene_subs.add_parser("add-dialogue-choice-flag", help="Wire a dialogue choice to setting a flag")
    p_dial.add_argument("scene_path", help="Path to scene JSON")
    p_dial.add_argument("--speaker-id", required=True, dest="speaker_id", help="Speaker entity id")
    p_dial.add_argument("--choice-id", required=True, dest="choice_id", help="Choice id")
    p_dial.add_argument("--choice-text", required=True, dest="choice_text", help="Choice text")
    p_dial.add_argument("--set-flag", required=True, dest="set_flag", help="Flag to set true")
    p_dial.add_argument("--require", action="append", default=[], help="Required flags (repeatable)")
    p_dial.add_argument("--forbid", action="append", default=[], help="Forbidden flags (repeatable)")
    p_dial.add_argument("--toast", help="Toast message")
    p_dial.add_argument("--toast-seconds", type=float, dest="toast_seconds", help="Toast duration (seconds)")
    p_dial.set_defaults(func=entities._handle_scene_add_dialogue_choice_flag)

    p_stamp = scene_subs.add_parser("stamp", help="Apply a stamp into a scene (idempotent)")
    p_stamp.add_argument("scene_path", help="Path to scene JSON")
    p_stamp.add_argument("--stamp", required=True, help="Path to stamp JSON")
    p_stamp.add_argument("--x", type=int, required=True, help="Origin tile X")
    p_stamp.add_argument("--y", type=int, required=True, help="Origin tile Y")
    p_stamp.add_argument("--id-prefix", dest="id_prefix", default="", help="Optional id prefix override")
    p_stamp.set_defaults(func=stamp._handle_scene_stamp)

    p_stamp_rep = scene_subs.add_parser("stamp-report", help="Dry-run stamp application and emit a report")
    p_stamp_rep.add_argument("scene_path", help="Path to scene JSON")
    p_stamp_rep.add_argument("--stamp", required=True, help="Path to stamp JSON")
    p_stamp_rep.add_argument("--x", type=int, required=True, help="Origin tile X")
    p_stamp_rep.add_argument("--y", type=int, required=True, help="Origin tile Y")
    p_stamp_rep.add_argument("--id-prefix", dest="id_prefix", default="", help="Optional id prefix override")
    p_stamp_rep.add_argument("--format", choices=["json", "text"], default="json", help="Output format")
    p_stamp_rep.set_defaults(func=stamp._handle_scene_stamp_report)

    p_macro_apply = scene_subs.add_parser("macro-apply", help="Apply a macro asset to a scene (idempotent)")
    p_macro_apply.add_argument("scene_path", help="Path to scene JSON")
    p_macro_apply.add_argument("--macro", required=True, help="Path to macro asset JSON")
    p_macro_apply.add_argument("--arg", action="append", default=[], help="Macro arg override k=v (repeatable)")
    p_macro_apply.add_argument("--anchor", choices=["primary", "cursor", "player"], help="Anchor override")
    p_macro_apply.set_defaults(func=macro._handle_scene_macro_apply)

    p_macro_rep = scene_subs.add_parser("macro-report", help="Dry-run macro and emit a deterministic report")
    p_macro_rep.add_argument("scene_path", help="Path to scene JSON")
    p_macro_rep.add_argument("--macro", required=True, help="Path to macro asset JSON")
    p_macro_rep.add_argument("--arg", action="append", default=[], help="Macro arg override k=v (repeatable)")
    p_macro_rep.add_argument("--anchor", choices=["primary", "cursor", "player"], help="Anchor override")
    p_macro_rep.add_argument("--format", choices=["json", "text"], default="json", help="Output format")
    p_macro_rep.set_defaults(func=macro._handle_scene_macro_report)

    p_prefab_diff = scene_subs.add_parser("prefab-diff", help="Show prefab overrides for an entity")
    p_prefab_diff.add_argument("--scene", required=True, help="Path to scene JSON")
    p_prefab_diff.add_argument("--entity", required=True, help="Entity id")
    p_prefab_diff.add_argument("--format", choices=["text", "json"], default="text", help="Output format")
    p_prefab_diff.set_defaults(func=prefab_overrides._handle_scene_prefab_diff)

    p_prefab_reset = scene_subs.add_parser("prefab-reset", help="Reset prefab overrides for an entity")
    p_prefab_reset.add_argument("--scene", required=True, help="Path to scene JSON")
    p_prefab_reset.add_argument("--entity", required=True, help="Entity id")
    reset_group = p_prefab_reset.add_mutually_exclusive_group(required=True)
    reset_group.add_argument("--field", help="Field path to reset (e.g. sprite or behaviour_config.X.y)")
    reset_group.add_argument("--all", action="store_true", help="Reset all overrides")
    p_prefab_reset.set_defaults(func=prefab_overrides._handle_scene_prefab_reset)


def handle(args: argparse.Namespace) -> int:
    func = getattr(args, "func", None)
    if callable(func):
        return cast(Callable[[argparse.Namespace], int], func)(args)
    return 0
